import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Adventure Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Adventure Log!</a>
        </h1>

        <p className={styles.description}>
         A web app designed for tracking simple stats and taking notes for tabletop RPGS.
        </p>

      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/mcclellangg">
          Created by Grayson McClellan
        </a>
      </footer>
    </div>
  )
}
